dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '12'
install: echo "install happens as part of setup"
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: 'edouardr-github'
    token:
      secure: 'bYujx95gSmStP3G95BLOwE+uNtxnhLfnIgtvFeZroLtnGUXM8Q3ajZ7Q8DKYpGhyDaCv8DvBoQLOrnvw3AGf2f7Grca0pKdZ5dTfnwv0EVQPs3Ovevr6rST+BBubnn+b/EwUmy2R1TaHM+az18ajMskChmQvZRNlpOAPtKZ793DxF5YlUvmVyQccqhk0BS1TJjHaJgupQca8iCB8Az+uHuXR6Tcurq0+QUnRX0s6vOTgoLVCAoEhHNgMD3lFB12Lk1m0KhQZQ747H67JgR7ZKB9Ce21afUcQXCR33+c2znQJtHMdpvZli76kmV5mApXbm+xgYm+WCPdAiIculNrpfbRmZKTKWHtNPXxrF3CmlUspkLa/bVfehmLp27kVf3VazPR0glXnPvgLR/DYoqcBW7sxsUPDt70iifYdv6cgDWp9UqMuhdJuzSEUSqOeeaTxZmTSxnmyeKCb8mtShmIHgkmzEy7Zx+8Nxi4xBSHUpNi9CMbMiIsa+FqF8WZF+OQ5sWSDMMe8rTu0E+I+3XWJAahT0D1Y5EIvQ+UXBetYuzNuW4oSNRNEvf/5GGKifaOFWr2PxKg0zSCFMsphquGKmCbQqsTgnTq7PEVWaxagAh+gP17wQumf9/3+e9HuGk3FOPxURyoRT9Nxjf13khkuQnvgbb/BxFP05G52ZhJnFrg='
script:
  - npm run setup
  - sonar-scanner
