image: node:8.11.1
clone:
  depth: full
pipelines:
    branches:
        master:
            - step:
              script:
                - npm install
                - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
